# This is a basic configuration file for deploying to Cloudflare Pages
# For static sites, just specify the output directory
[build]
command = ""

[build.environment]
NODE_VERSION = "20"

[site]
bucket = "."
